### ISSUE TITLE
Collect Codes of Conduct?

### ISSUE THREAD

**Issue by RichardLitt** [sustainers/dei-handbook#4]
Perhaps we should have a page about CoCs?

**Comment by Anita-ihuman** [comment]
I think this would make a great add: Putting a few that I came across in the reources

**Comment by gvlx** [comment]
first on the list: https://github.com/EthicalSource/contributor_covenant

**Comment by glauesppen** [comment]
@RichardLitt added here https://sustainoss.org/dei-handbook/landscape.html#code-of-conduct-guides
Please let me know if this was what you were thinking. If so, we can close the issue :)

**Comment by RichardLitt** [comment]
This is great, thanks!
